name: Test

on:
  push:
    paths:
      - "edition-nft/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '1.16'
      - run: cd edition-nft && make test